model:
  type: "mpgnn"
  gnn_layers: 8
  mlp_output_size: 16
  mlp_layers: 4
  mlp_channels: 128
  weight_mlp_layers: 4
  weight_mlp_channels: 16
  weighted_mp: False
  use_edge_weights: True
  use_node_weights: True
  norm: "batch_norm"
loss:
  add_bce: True
  bce_constraints: True
  lambda_bce : 0.2
dataset:
  data_type : "homogeneous"
  data_dir: "/home/sutclw/weighted_MP_gnn/truth_Bd_DD_5k"
training:
  train: True
  starting_learning_rate: 0.001
  batch_size: 8
  dropped_lr_epochs: 2
  epochs: 30
  model_file: "Final_full_graph_8block_32_epochs_weighted_message_passing_BCE.pt"
inference:
#  model_file: "/home/sutclw/full_graph_results2/Final_full_graph_8block_32_epochs_weighted_message_passing_BCE.pt"
  model_file: "../bn_trainings/Final_full_graph_8block_36_epochs_message_passing_BCE_hadronic_cocktail_shuffle_bnorm.pt"
  name: "had_B_DD_wmp_BCE_full_graphs"  
  results_dir: "/home/sutclw/Work/Zurich/LHCb/GNNs/paper_results/B_DD_wmpgnn_had"
