model:
  type: "heterognn"
  gnn_layers: 8
  mlp_output_size: 16
  mlp_layers: 4
  mlp_channels: 128
  weight_mlp_layers: 4
  weight_mlp_channels: 16
  weighted_mp: True
  use_edge_weights: True
  use_node_weights: True
  node_types: ['tracks', 'pvs']
  edge_types: ["tracks_tracks","tracks_pvs"]
loss:
  add_bce: True
  beta_edge_bce : 0.2
  beta_node_bce : 0.2
  beta_pv_bce : 0.2
dataset:
  data_type: "heterogeneous"
  data_dir: "/home/sutclw/weighted_MP_gnn/bdtprunedgraphs_cached_data_49193"
training:
  train: True
  starting_learning_rate: 0.001
  epochs: 30
  dropped_lr_epochs: 2
  batch_size: 32
  model_file: "Final_hetero_8block_32_epochs_message_passing_BCE.pt"
inference:

  inference: True
  learning_rate: 0.001
  batch_size: 32