model:
  type: "heterognn"
  gnn_layers: 3
  mlp_output_size: 16
  mlp_layers: 4
  mlp_channels: 128
  weight_mlp_layers: 4
  weight_mlp_channels: 16
  weighted_mp: False
  use_edge_weights: True
  use_node_weights: True
  node_types: ['tracks', 'pvs']
  edge_types: ["tracks_tracks","tracks_pvs"]
  norm: "batch_norm"
  LCA_classes: 3
loss:
  add_pv: True
  beta_bce_nodes : 3
  beta_bce_edges : 33
  beta_bce_pvs : 1
dataset:
  event_type: 1
  data_type: "heterogeneous"
  data_dir: '/user/gr1/lhcb/scapelli/DFEI/lhcbdfei/data_handling/input_formatting/run3_onlyLong_magup'
  evt_max_train: 80
  evt_max_val: 100
  evt_max_test: 0
training:
  train: True
  random_seed: 420
  starting_learning_rate: 0.002
  epochs: 1
  dropped_lr_epochs: 0
  early_stopping: 0
  batch_size: 8
  load_checkpoint: False
  save_checkpoint: True
  model_file: "Final_{dataset_data_type}_{model_gnn_layers}block_{training_epochs}_epochs_{training_starting_learning_rate}LR_{training_batch_size}batch_message_passing_BCE_{model_LCA_classes}LCA_onlyLongUp_newLoss.pt"
inference:
  model_file: "outputs/Final_heterogeneous_12block_30_epochs_0.003LR_16batch_message_passing_BCE_5LCA_onlyLongUp/Final_heterogeneous_12block_30_epochs_0.003LR_16batch_message_passing_BCE_5LCA_onlyLongUp.pt"
  name: "test_hetero_wmp_BCE_full_graphs"
  results_dir: "test_output/test_hetero_wmpgnn"