model:
  type: "heterognn"
  gnn_layers: 8
  mlp_output_size: 16
  mlp_layers: 4
  mlp_channels: 128
  weight_mlp_layers: 4
  weight_mlp_channels: 16
  weighted_mp: True
  use_edge_weights: True
  use_node_weights: True
  node_types: ['tracks', 'pvs']
  edge_types: ["tracks_tracks","tracks_pvs"]
loss:
  add_bce: True
  beta_edge_bce : 0.2
  beta_node_bce : 0.2
  beta_pv_bce : 0.2
dataset:
  data_type: "heterogeneous"
#  data_dir: "/home/sutclw/weighted_MP_gnn/bdtprunedgraphs_cached_data_49193"
#  data_dir: "/home/sutclw/weighted_MP_gnn/fullgraphs_cached_data_49193"
#  data_dir: "/media/sutclw/WILLSSD/fullgraphs_cached_data_49193/fullgraphs_cached_data_49193"
  data_dir: /home/sutclw/weighted_MP_gnn/full_graphs_Bd_Kpi
training:
  train: True
  starting_learning_rate: 0.001
  epochs: 30
  dropped_lr_epochs: 2
  batch_size: 32
  model_file: "Final_hetero_8block_32_epochs_message_passing_BCE.pt"
inference:
  #model_file: "/home/sutclw/full_graph_results2/Final_full_graph_hetero_8block_32_epochs_weighted_message_passing_BCE.pt"
  model_file: "/home/sutclw/Final_full_graph_hetero_8block_38_epochs_weighted_message_passing_BCE.pt"
  #model_file: "/home/sutclw/full_graph_results2/Final_full_graph_hetero_8block_32_epochs_weighted_message_passing_BCE.pt"
#  model_file: "/home/sutclw/results2/results2/Final_hetero_8block_32_epochs_weighted_message_passing_BCE.pt"
#  model_file: "/home/sutclw/results2/results2/Final_hetero_8block_32_epochs_weighted_message_passing_pv_constraints.pt"
#  name: "hetero_8block_wmp_BCE_full_graph"
  name: "Bd_Kpi_hetero_wmp_BCE_full_graphs"  
  results_dir: "/home/sutclw/Work/Zurich/LHCb/GNNs/paper_results/Bd_Kpi_hetero_wmpgnn"
