# YAML file example: config.yaml

model:
  type: "mpgnn"
  gnn_layers: 4
  mlp_output_size: 16
  mlp_layers: 4
  mlp_channels: 128
  weight_mlp_layers: 3
  weight_mlp_channels: 16
  weighted_mp: False
  use_edge_weights: True
  use_node_weights: True
loss:
  bce_constraints: True
  lambda_bce : 0.2
dataset:
  data_type : "homogeneous"
  data_dir: /home/sutclw/Work/Zurich/LHCb/GNNs/cached_LCA_training_events_PYTHIA
training:
  train: True
  starting_learning_rate: 0.001
  batch_size: 32
inference:
  inference: True
  learning_rate: 0.001
  batch_size: 32