# YAML file example: config.yaml

model:
  type: "mpgnn"
  gnn_layers: 8
  mlp_output_size: 16
  mlp_layers: 4
  mlp_channels: 128
  weight_mlp_layers: 4
  weight_mlp_channels: 16
  weighted_mp: True
  use_edge_weights: True
  use_node_weights: True
  norm: "batch_norm"
  LCA_classes: 5
loss:
  bce_constraints: True
  lambda_bce : 0.2
dataset:
  data_type : "homogeneous"
  data_dir: /user/gr1/lhcb/scapelli/DFEI/lhcbdfei/data_handling/input_formatting/run3
training:
  train: True
  starting_learning_rate: 0.001
  epochs: 3
  dropped_lr_epochs: 2
  batch_size: 32
  model_file: "Final_{dataset_data_type}_{model_gnn_layers}block_{training_epochs}_epochs_message_passing_BCE.pt"
inference:
  inference: True
  learning_rate: 0.001
  batch_size: 32