model:
  type: "mpgnn"
  gnn_layers: 8
  mlp_output_size: 16
  mlp_layers: 4
  mlp_channels: 128
  weight_mlp_layers: 4
  weight_mlp_channels: 16
  weighted_mp: False
  use_edge_weights: True
  use_node_weights: True
  norm: "batch_norm"
loss:
  add_bce: True
  bce_constraints: True
  lambda_bce : 0.2
dataset:
  data_type : "homogeneous"
#  data_dir: /home/sutclw/weighted_MP_gnn/bdtprunedgraphs_cached_data_49193
#  data_dir: /home/sutclw/weighted_MP_gnn/full_graphs_Bs_Jpsiphi
#  data_dir: /home/sutclw/weighted_MP_gnn/bdt_pruned_Bs_Jpsiphi
#  data_dir: /home/sutclw/weighted_MP_gnn/full_graphs_Bd_Kstmumu
#  data_dir: /home/sutclw/weighted_MP_gnn/bdt_pruned_Bd_Kstmumu
#  data_dir: /home/sutclw/weighted_MP_gnn/unfiltered_cached_data_49193#
  data_dir: /home/sutclw/weighted_MP_gnn/truth_inclusive_10k_49193
#  data_dir: /home/sutclw/weighted_MP_gnn/truth_Bd_Kstmumu_5k
#  data_dir: /home/sutclw/weighted_MP_gnn/truth_Bs_Jpsiphi_5k
#  data_dir: /home/sutclw/weighted_MP_gnn/truth_Bd_DD_5k
#  data_dir: /home/sutclw/weighted_MP_gnn/truth_Bd_Kpi_5k
#  data_dir: /home/sutclw/weighted_MP_gnn/truth_Bu_Kmumu_5k

#  data_dir: /home/sutclw/weighted_MP_gnn/truth_Lb_Lcpi_5k
#  data_dir: /home/sutclw/weighted_MP_gnn/truth_Bs_Dspi_5k
#  data_dir: /home/sutclw/weighted_MP_gnn/truth_Bd_Kstmumu_5k
#  data_dir: /home/sutclw/weighted_MP_gnn/truth_Tbc_DJpsiX
#  data_dir:  /home/sutclw/weighted_MP_gnn/truth_Bu_Kmumu_5k
#  data_dir: /home/sutclw/weighted_MP_gnn/truth_bdtpruned_Bs_Jpsiphi_5k
#  data_dir: /home/sutclw/weighted_MP_gnn/truth_bdtpruned_inclusive_10k_49193
training:
  train: True
  starting_learning_rate: 0.001
  batch_size: 8
  dropped_lr_epochs: 2
  epochs: 30
  model_file: "Final_full_graph_8block_32_epochs_weighted_message_passing_BCE.pt"
inference:
#  model_file: "/home/sutclw/full_graph_results2/Final_full_graph_8block_32_epochs_weighted_message_passing_BCE.pt"
#  model_file: "../Final_full_graph_8block_32_epochs_weighted_message_passing_BCE_hadronic_cocktail.pt"
#  model_file: "../bn_trainings/Final_full_graph_8block_36_epochs_message_passing_BCE_hadronic_cocktail_shuffle_bnorm.pt"
  model_file: "../bn_trainings/Final_full_graph_8block_36_epochs_message_passing_BCE_batch_norm.pt"

  #model_file: "../bn_trainings/Final_full_graph_8block_32_epochs_message_passing_BCE_hadronic_cocktail_shuffle_bnorm.pt"
  name: "test_wmp_BCE_full_graphs"  
  results_dir: "/home/sutclw/Work/Zurich/LHCb/GNNs/paper_results/testrun_wmpgnn"
#  model_file: "../bn_trainings/Final_full_graph_8block_36_epochs_message_passing_BCE_batch_norm.pt"
#  model_file: "../bn_trainings/Final_full_graph_8block_32_epochs_weighted_message_passing_batch_norm.pt"
#  model_file: "../bn_trainings/Final_full_graph_8block_36_epochs_weighted_message_passing_BCE_hadronic_cocktail_shuffle_bnorm.pt"
#  model_file: "../bn_trainings/Final_full_graph_8block_32_epochs_weighted_message_passing_BCE_hadronic_cocktail_shuffle_bnorm.pt"
#  model_file: "Final_model_8block_32epochs_weighted_message_passing_19Feb25_bdt_pruned.pth"
#  model_file: "/home/sutclw/Final_full_graph_8block_42_epochs_weighted_message_passing_BCE_hadronic_finetuned.pt"
#  model_file: "/home/sutclw/results/Final_model_8block_32epochs_message_passing_3Feb25.pth"
#  model_file: "/home/sutclw/results/Final_model_8block_32epochs_weighted_message_passing_BCE_3Feb25.pth"